version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "prisma-cloud-remediation"
s3_bucket = "aws-sam-prisma-function"
s3_prefix = "prisma"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
