AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PrimsVPCKiller:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::907984961736:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                "sts:ExternalId": "PrismaVPCKiller"
      RoleName: Prisma_VPC_Term_Role
      Policies:
        - PolicyName: PrismaVPCTerminator
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:Describe*'
                  - 'ec2:DeleteSecurityGroup'
                  - 'ec2:DeleteSubnet'
                  - 'ec2:DeleteVpc'
                  - 'ec2:DeleteInternetGateway'
                  - 'ec2:TerminateInstances'
                  - 'ec2:DetachInternetGateway'
                Resource: '*'
              - Action:
                  - 'ec2:Delete*'
                  - 'ec2:TerminateInstances'
                Effect: Deny
                Resource: '*'
                Condition:
                  StringEquals:
                    "aws:RequestedRegion": "us-east-1"